name: Sentiment Analysis

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sentiment analysis
        run: |
          python sentiment_analysis.py

      - name: Setup CML
        uses: iterative/setup-cml@v2
        with:
          version: latest
          vega: true

      - name: Run CML
        run: |
          cml run --partition=cml-dpart --qos=cml-medium --account=cml-tomg --gres=gpu:rtx2080ti:2
